{{ if .Values.cronJob.create }}
{{ range .Values.cronJob.crons }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
  {{- include "service.labels" $ | nindent 4 }}
spec:
  schedule: {{ .schedule | quote }}
  {{- with .concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        {{- with .annotations }}
        metadata:
          annotations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        spec:
          {{- with .serviceAccount }}
          serviceAccountName: {{ . }}
          {{- end }}
          containers:
          {{- toYaml .containers | nindent 12 }}
          restartPolicy: {{ .restartPolicy }}
          {{- with $.Values.nodeSelectorLabels }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---          
{{ end }}
{{ end }}