{{- $country := $.Values.country }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
  {{- include "service.labels" . | nindent 4 }}
  {{- if .Values.datadog.enabled }}
    {{- include "datadog.labels" . | nindent 4 }}
  {{- end }}
  {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  {{- if eq $country "ksa" }}
  replicas: {{ .Values.ksareplicaCount }}
  {{- else }}
  replicas: {{.Values.replicaCount}}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.vaultAgent.enabled }}
        {{- toYaml .Values.vaultAgent.annotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
        {{- if .Values.datadog.enabled }}
          {{- include "datadog.labels" . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        {{- with .Values.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelectorLabels }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.vaultAgent.enabled }}
      serviceAccountName: {{ .Values.vaultAgent.serviceAccount }}
      {{- else }}
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8}}
      {{- end }}
      containers:
      - name: {{ include "service.name" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
        {{- with .Values.livenessProbe }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        readinessProbe:
        {{- with .Values.readinessProbe }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        startupProbe:
        {{- with .Values.startupProbe }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        env: 
        {{- if .Values.containerEnv }}
{{ (tpl ( toYaml .Values.containerEnv) .) | indent 12 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.volumeMounts }}
          {{- toYaml .Values.volumeMounts | nindent 12}}
        {{- end }}